### ISSUE TITLE
docs.rs can't build

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/couchbase-rs#12]
See my comment in https://github.com/onur/docs.rs/issues/23#issuecomment-275991647 it looks like the docs.rs machines are missing libevent which is needed for libcouchbase to compile

**Comment by daschl** [comment]
fixed!

**Comment by adililhan** [comment]
still can't build it: https://docs.rs/crate/couchbase-sys/

I just tried install ```couchbase-sys``` via Cargo on my computer as well. I got same error: ```"Need to build libcouchbase (none found), but the 'build-lcb' feature is not enabled!"```

I've already installed `libcouchbase` `clang` `libclang` though.

**Comment by daschl** [comment]
@adililhan thanks.. on which OS are you on? One thing I was considering is just building by default if not found and only disable with an env variable if you don't want that? its a bit tricky to get all the situations right.

**Comment by adililhan** [comment]
It's Ubuntu 16.04.3 LTS.

```One thing I was considering is just building by default if not found and only disable with an env variable if you don't want that?```

I didn't get it. What can I disable with an env variable?

Besides, docs.rs can't build it either. According to your previous comments, it was ok. Could there be a problem with cmake?

**Comment by daschl** [comment]
right now it uses pkg-config to probe for `libcouchbase` https://github.com/couchbaselabs/couchbase-rs/blob/master/couchbase-sys/build.rs#L51 .. can you check on your command line if it finds it there?

**Comment by adililhan** [comment]
yes, I have `libcouchbase`:

```
root@couchbase1:~# pkg-config --list-all | grep couch
libcouchbase      libcouchbase 2.8.3 - Couchbase client library
```

**Comment by adililhan** [comment]
I resolved the issue thanks to this instruction: https://github.com/couchbaselabs/couchbase-rs/issues/35
